version: '3.8'

services:
  app:
    image: juan321/ms_content_moderator:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    secrets:
      - DATABASE_URL
      - DATABASE_USERNAME
      - DATABASE_PASSWORD
    environment:
      DATABASE_URL_FILE: /run/secrets/DATABASE_URL
      DATABASE_USERNAME_FILE: /run/secrets/DATABASE_USERNAME
      DATABASE_PASSWORD_FILE: /run/secrets/DATABASE_PASSWORD

secrets:
  DATABASE_URL:
    external: true
  DATABASE_USERNAME:
    external: true
  DATABASE_PASSWORD:
    external: true
