server:
  port: 8085

spring:
  application:
    name: ms_content_moderator
  r2dbc:
    url: ${{ DATABASE_URL }}
    username: ${{ DATABASE_USERNAME }}
    password: ${DATABASE_PASSWORD}
  contentmoderator:
    apikey: ${API_KEY}
