server:
  port: 8085

spring:
  application:
    name: ms_content_moderator
  r2dbc:
    #url: r2dbc:postgresql://localhost:5432/content_moderator
    url: r2dbc:postgres://batyr.db.elephantsql.com:5432/mkyhttrp
    username: mkyhttrp
    password: BrP3JjzyN_CDYObMB3AgTUs5WdfbIPW7
    #url: ${{secrets.DATABASE_URL}}
    #username: ${{secrets.DATABASE_USERNAME}}
    #password: ${{secrets.DATABASE_PASSWORD}}
  contentmoderator:
    apikey: 8150ba9e33824e3a9ff48a5f29eeb7ce
