server:
  port: 8085

spring:
  application:
    name: ms_content_moderator
  r2dbc:
    url: r2dbc:pool:postgres://batyr.db.elephantsql.com:5432/mkyhttrp
    username: mkyhttrp
    password: BrP3JjzyN_CDYObMB3AgTUs5WdfbIPW7
