server:
  port: 8085

spring:
  application:
    name: ms_content_moderator
  r2dbc:
    #url: r2dbc:postgresql://localhost:5432/content_moderator
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    
    #url: r2dbc:postgres://batyr.db.elephantsql.com:5432/mkyhttrp
    #username: mkyhttrp
    #password: BrP3JjzyN_CDYObMB3AgTUs5WdfbIPW7
    
    #url: ${{secrets.DATABASE_URL}}
    #username: ${{secrets.DATABASE_USERNAME}}
    #password: ${{secrets.DATABASE_PASSWORD}}
  contentmoderator:
    apikey: ${API_KEY}