# kubectl apply -f deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-moderator-be
  namespace: juan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-moderator-be
  template:
    metadata:
      labels:
        app: content-moderator-be
    spec:
      containers:
      - name: content-moderator-be
        image: juan321/ms_content_moderator_be:latest   # Reemplaza con tu imagen Docker
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-credentials                # Nombre del Secret
              key: DATABASE_URL                         # Clave dentro del Secret
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: DATABASE_USERNAME
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: DATABASE_PASSWORD
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: API_KEY
