name: Docker Hub
on:
  push:
    branches:
      - develop-spring-boot

jobs:
  build_dockerhub:
    name: Build and Push Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'
    - name: Build With Maven
      run: mvn clean install

    - name: Build Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        dockerfile: Dockerfile
        push: false
        tags: ${{ secrets.DOCKER_USERNAME }}/ms_content_moderator:latest

    - name: docker login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image to Docker Hub
      uses: docker/build-push-action@v4
      with:
        context: .
        dockerfile: Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/ms_content_moderator:latest
